name: github-actions-runner
services:
  worker:
    image: myoung34/github-runner:latest
    container_name: github-actions-runner
    restart: unless-stopped

    env_file:
      - .github_runner.env

    environment:
      # Organization-level runner configuration
      RUNNER_SCOPE: 'org'
      ORG_NAME: ${ORG_NAME:-stanstrup-metabolomics}
      RUNNER_NAME_PREFIX: ${RUNNER_NAME_PREFIX:-docker-runner}
      RUNNER_GROUP: ${RUNNER_GROUP:-default}
      LABELS: ${LABELS:-docker,linux}

      # Working directories
      RUNNER_WORKDIR: /tmp/runner/work
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data

      # Optional settings
      EPHEMERAL: ${EPHEMERAL:-false}
      DISABLE_AUTO_UPDATE: ${DISABLE_AUTO_UPDATE:-false}
      
      DISABLE_AUTOMATIC_DEREGISTRATION: true

    security_opt:
      - label:disable

    volumes:
      # Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Runner configuration and state
      - /mnt/z/docker/config_dirs/github-runner/data:/runner/data
      # Runner workspace
      - /mnt/z/docker/config_dirs/github-runner/work:/tmp/runner/work

    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
