version: '3.8'

services:
  github-runner:
    image: ghcr.io/actions/runner:latest
    container_name: github-actions-runner
    restart: unless-stopped

    # Automatically load environment variables from .github_runner.env
    env_file:
      - .github_runner.env

    environment:
      # Defaults (can be overridden in .github_runner.env)
      REPO_URL: ${REPO_URL:-https://github.com/stanstrup/rePredRet}
      RUNNER_NAME: ${RUNNER_NAME:-docker-runner-1}
      RUNNER_WORK: /home/runner/work
      RUNNER_LABELS: ${RUNNER_LABELS:-docker,linux}
      EPHEMERAL: ${EPHEMERAL:-false}

    volumes:
      # Mount Docker socket to allow Docker in Docker (dind)
      - /var/run/docker.sock:/var/run/docker.sock

      # Work directory for actions
      - runner-work:/home/runner/work

      # Optional: persist runner config between restarts
      - runner-config:/home/runner/.runner-config

    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

    # Allow privileged mode for Docker operations
    privileged: true

    # Keep the container running
    command: bash -c "cd /home/runner && bash /entrypoint.sh"

volumes:
  runner-work:
  runner-config:
